### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by wakaeri** [wakaeri/protospace-38531#1]
#URL
https://protospace-38531.onrender.com/

**Comment by ghost** [comment]
@wakaeri さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**

**ユーザー詳細機能**
- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
プロトタイプ詳細ページの上部にあるユーザー名をクリックしても、該当するユーザーの詳細ページに遷移できない状態です。
該当するユーザーの詳細ページに遷移できるようにしましょう。

https://user-images.githubusercontent.com/116065064/215365066-ea81dbb3-756e-436b-9754-1d6a999a03c4.mov




修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
挙動確認を行い、修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by wakaeri** [comment]
> https://forms.gle/ZdLeprTTWhMA8aZA7

ご確認ありがとうございました。修正しました。ご査収よろしくお願いいたします。

**Comment by ghost** [comment]
@wakaeri さん、ご提出ありがとうございます‼︎
また、ご丁寧にご対応いただきありがとうございます。
正常に動作することが確認できました!　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！
今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
